/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juezvirtual;

import java.applet.AudioClip;
import java.awt.Desktop;
import java.net.URI;
import java.net.URL;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Angelo
 */
public class frmJuez extends javax.swing.JFrame {

    URL url;
    AudioClip ac;
    boolean reproduciendo = false;
    int tiempoReproducido = 0;
    Timer timy;
    TimerTask taskCosmo;
    /**
     * Creates new form frmJuez
     */
    public frmJuez() {
        initComponents();
        txtRunner.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl = new javax.swing.JLabel();
        txtRunner = new javax.swing.JTextField();
        txtJuez = new javax.swing.JTextField();
        btnCsTimer = new javax.swing.JButton();
        btnCubingMusic = new javax.swing.JButton();
        btnAmbos = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl.setText("Entre a la caja de texto y presione enter para iniciar o detener el audio");

        txtRunner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRunnerActionPerformed(evt);
            }
        });

        txtJuez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJuezActionPerformed(evt);
            }
        });

        btnCsTimer.setText("Abrir csTimer");
        btnCsTimer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCsTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCsTimerActionPerformed(evt);
            }
        });

        btnCubingMusic.setText("Abrir cubing music");
        btnCubingMusic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCubingMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCubingMusicActionPerformed(evt);
            }
        });

        btnAmbos.setText("Abrir csTimer y cubing music");
        btnAmbos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAmbos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmbosActionPerformed(evt);
            }
        });

        lbl1.setText("Entre a la caja de texto y presione enter para que el runner lo llame");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCubingMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAmbos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtJuez)
                            .addComponent(btnCsTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRunner)
                            .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRunner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJuez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCsTimer)
                .addGap(18, 18, 18)
                .addComponent(btnCubingMusic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAmbos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJuezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJuezActionPerformed
        // TODO add your handling code here:
        if(reproduciendo == false)
        {
            reproducirVozJuez();
            txtJuez.setText("");
            txtRunner.requestFocus();
        }
        else 
        {
            detenerVozJuez();
        }
    }//GEN-LAST:event_txtJuezActionPerformed

    private void btnCsTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCsTimerActionPerformed
        // TODO add your handling code here:
        abrirCsTimer();
        txtJuez.requestFocus();
    }//GEN-LAST:event_btnCsTimerActionPerformed

    private void btnCubingMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCubingMusicActionPerformed
        // TODO add your handling code here:
        abrirCubingMusic();
        txtJuez.requestFocus();
    }//GEN-LAST:event_btnCubingMusicActionPerformed

    private void btnAmbosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmbosActionPerformed
        // TODO add your handling code here:
        abrirCubingMusic();
        abrirCsTimer();
        txtJuez.requestFocus();
    }//GEN-LAST:event_btnAmbosActionPerformed

    private void txtRunnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRunnerActionPerformed
        // TODO add your handling code here:
        txtJuez.requestFocus();
        System.out.println("El runner te llamará pronto");
        iniciarVozRunner();
    }//GEN-LAST:event_txtRunnerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJuez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJuez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJuez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJuez.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJuez().setVisible(true);
            }
        });
    }
    
    private void reproducirVozJuez()
    {
        try
        {
            url = this.getClass().getResource("vozJuez.wav");
            ac =  audioJuezApplet.newAudioClip(url);
            ac.play();
            reproduciendo = true;
            iniciarTimer();
        }
        catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void detenerVozJuez()
    {
        ac.stop();
        timy.cancel();
        reproduciendo = false;
    }
    
    private void reproducirVozRunner()
    {
        try
        {
            url = this.getClass().getResource("vozRunner.wav");
            ac =  audioJuezApplet.newAudioClip(url);
            ac.play();
        }
        catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void iniciarTimer()
    {
        tiempoReproducido = 0;
        timy = new Timer();
        taskCosmo = new TimerTask()
                {
            @Override
            public void run()
            {
                actualizarTiempo();
                System.out.println(tiempoReproducido);
            }
        };
        timy.scheduleAtFixedRate(taskCosmo, 0, 1000);
    }
    
    private void abrirCsTimer()
    {
        abrirUrl("https://cstimer.net/");
    }
    
    private void abrirCubingMusic()
    {
        abrirUrl("https://www.youtube.com/watch?v=bM7SZ5SBzyY&index=1&list=PLDmwRKL4MfeKD20-llhNblggJVmxiIcvU");
    }
    
    public void abrirUrl(String link)
    {
        try
        {
            if(Desktop.isDesktopSupported())
            {
                Desktop desktop = Desktop.getDesktop();
                if(desktop.isSupported(Desktop.Action.BROWSE))
                {
                    desktop.browse(new URI(link));
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void actualizarTiempo()
    {
        tiempoReproducido++;
        if(tiempoReproducido == 10)
        {
            ac.stop();
            timy.cancel();
            reproduciendo = false;
        }
    }
    
    private int segundosAleatorios()
    {
        return (int) (Math.random() * 7) + 1 + 8;
    }
    
    private void iniciarVozRunner()
    {
        try
        {
            Thread.sleep(1000*segundosAleatorios());
            System.out.println("El runner te está llamando.");
            reproducirVozRunner();
        }
        catch (InterruptedException ex)
        {
            Logger.getLogger(frmJuez.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmbos;
    private javax.swing.JButton btnCsTimer;
    private javax.swing.JButton btnCubingMusic;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextField txtJuez;
    private javax.swing.JTextField txtRunner;
    // End of variables declaration//GEN-END:variables
}
